version: '2'

services:
  web:
    build: ./docker/web
    links:
      - db
    volumes:
      - ./:/app:rw
    ports:
      - "80"
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: password
